### ISSUE TITLE
On dialog definition event is not working

### ISSUE THREAD

**Issue by codeforsure** [ckeditor/ckeditor4-react#67] opened 2019-10-16 09:50 UTC
## Are you reporting a feature request or a bug?

calling on DialogDefinition event in the ckeditor4-react npm package doesn't work

## Provide detailed reproduction steps (if any)
<CKEditor
      data={'random'}
      config={{
        filebrowserUploadUrl: 'random/',
        uploadUrl: '',
      }}
      onChange={e => {e.editor.getData (); }}
      onDialogDefinition={ev => console.log (ev)  }
      onFileUploadRequest={e => console.log (e)}
    />

### Expected result

on dialogDefinition event should be logged
### Actual result

no event is seen

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by ishindanil** [comment] 2019-10-16 13:13
I think your problem is related to this.
https://stackoverflow.com/a/31427109

`ckeditor4-react` applies handlers to an editor instance as you can see here:
https://github.com/ckeditor/ckeditor4-react/blob/9e5955f1c81c8670e460e2cf69352eae6e324fad/src/ckeditor.jsx#L98

**Comment by codeforsure** [comment] 2019-10-17 06:32
Actually I need to add some html to image plugin and change some names, I done it in onDialogDefinition Event. Is there any other way to do it

**Comment by Comandeer** [comment] 2019-11-04 16:04
Sorry for the late response!

You can use `dialogDefinition` event inside `onBeforeLoad`:

```jsx
<CKEditor
	onBeforeLoad = { ( CKEDITOR ) => CKEDITOR.on( 'dialogDefinition', someFn ) }
/>
```

**Comment by codeforsure** [comment] 2019-11-06 09:09
I was using the same but, I am adding a custom button in image plugin some times the button is showing more than one time . I can't reproduce why this is happening since it is occuring randomly

**Comment by f1ames** [comment] 2019-11-12 10:11
@codeforsure that shouldn't happen TBH. Make sure that your `dialogDefinition` listener is attached only once. Alternatively, you can add some extra check to see if your custom button was already added in your listener.

**Comment by codeforsure** [comment] 2019-11-12 10:18
Actually, I am using custom check and it is working. But, I am not sure why the dialogDefinition is attaching 'n' times( I am loading the editor component not the whole page on event) for 'n' loads of editor component

**Comment by Comandeer** [comment] 2019-12-13 20:57
It's caused by the fact that for now `onBeforeLoad` runs for every editor's instance. Probably the easiest workaround would be to use some kind of a flag:

```javascript
let attached = false;

<CKEditor
	onBeforeLoad = { ( CKEDITOR ) => { !attached && CKEDITOR.on( 'dialogDefinition', someFn ); attached = true; } }
/>
```

**Comment by f1ames** [comment] 2019-12-16 08:39
I assume that `onBeforeLoad` works like that by design, However, we lack any documentation for this behavior so it should be added describing how it works.

**Comment by f1ames** [comment] 2020-01-09 15:43
Closing as we will proceed further in #77.

**Closed by f1ames** 2020-01-09 15:43 UTC
Labels: question

**Comment by Darkilen** [comment] 2021-01-22 09:05
Another solution is to use `CKEDITOR.once()` instead of `CKEDITOR.on()`, so it would run only once for this editor instance. If we have two instance with the same event (or differents events), they wouldn't override/overlaps each others.
