### ISSUE TITLE
Error for undo redo on data update

### ISSUE THREAD

**Issue by abhijitkc** [ckeditor/ckeditor4-react#139] opened 2020-10-14 09:00 UTC
## Bug

In ckeditor I have project content and there are multiple versions of projects. I am fetching the data from the database for project and its version. I am using only one instance for projects and its version. And I am getting the errors from below screenshot.
 
![error](https://user-images.githubusercontent.com/36158867/95967330-c2d32e80-0e29-11eb-84c1-e67b1f1a4ca5.png)

## Provide detailed reproduction steps (if any)

1. Fetch content from database and change some content.
2. then do the actions undo and redo.
3. Until I change the content everything works fine. But if I change the content to any version or back to projects then I got the error from the screenshot.

### Expected result

Undo redo should work as single instance and it should not have any error.

### Actual result

As I change the project versions contents I got the error from the screenshot.

## Other details

* Browser: Chrome and Safari
* OS: All
* Integration version: 4.13.1
* CKEditor version: 4
* Installed CKEditor plugins: richcombo, lineheight, divarea, indentblock, indentlist, indent, jqueryspellchecker, 
a11yhelp,
about,
autosave,
clipboard,
colordialog,
dialog,
div,
divarea,
find,
flash,
forms,
iframe,
image,
indent,
indentblock,
indentlist,
jqueryspellchecker,
lineheight,
link,
liststyle,
liTab,
magicline,
pagebreak,
pastefromword,
preview,
richcombo,
scayt,
showblocks,
smiley,
specialchar,
table,
tabletools,
templates,
textindent,
timestamp,
uicolor,
wordcount,
wsc

**Comment by Dumluregn** [comment] 2020-10-16 11:06
Hello,
as you can check in our [React integration sample](https://ckeditor.com/docs/ckeditor4/latest/examples/react.html#/), the issue is not reproducible (undo/redo works correctly and no errors are thrown). Are you able to provide a demo showing the issue?

**Comment by Comandeer** [comment] 2020-10-31 21:47
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2020-10-31 21:47 UTC
Labels: status:pending
