### ISSUE TITLE
 CKeditor 4 sometimes doesn't appear on react

### ISSUE THREAD

**Issue by fajrulaulia** [ckeditor/ckeditor4-react#71] opened 2019-12-20 09:27 UTC
Hi, I'm a reactjs developer, ckeditor 4 are sometimes Load & show,  sometimes not, maybe anyone knows possibility this throuble.

**Comment by msamsel** [comment] 2019-12-20 11:59
Please provide more details about the issue, to help us understand the reported issue.
How you have configured editor, how you are using it. Maybe you can provide some demo page or other types of samples, where issue exists and which can be inspected by us? What is your environment, what browser you're using, etc.

**Comment by fajrulaulia** [comment] 2019-12-30 11:07
I Apply it in Render.
``` js
.................
<textarea
      className="editor"
      name={this.state.id}
      id={this.state.id}
      rows={this.props.rows || "10"}
      cols={this.props.cols || "80"}
      value={this.props.content}
      onChange={e => console.log(e)}
 >
.................
```


this config
```
/**
 * Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

CKEDITOR.editorConfig = function( config ) {
  config.language = 'id';
  config.plugins += ",embedimage,cdlpagebreak,spacingsliders,cdltabtoindent,cdlliststyle";
  config.pasteFromWordCleanupFile = '/custom-pwf.js';
  config.fontSize_sizes = '7/7pt;9/9pt;11/11pt;13/13pt;15/15pt;17/17pt;20/20pt;30/30pt;40/40pt;';
  config.entities_additional = '#9';
  config.entities_processNumerical = 'force'; 
  config.extraPlugins = 'image2';
  config.removePlugins = 'image';
};

```

I use Reactjs and Chrome Browser

**Comment by fajrulaulia** [comment] 2020-01-08 08:28
this is a log when ckeditor cant load in reactjs

```
Uncaught TypeError: Cannot read property 'unselectable' of null
    at e (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:340)
    at c.<anonymous> (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:336)
    at c.f (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:10)
    at c.<anonymous> (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:11)
    at c.fire (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:13)
    at c.fireOnce (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:12)
    at c.fireOnce (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:13)
    at Object.<anonymous> (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:264)
    at b (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:245)
    at Array.n (ckeditor.js?__WB_REVISION__=e7e650a3d2af38284e9774d2053785e3:245)
```

**Comment by f1ames** [comment] 2020-01-09 15:07
Thanks for the details @fajrulaulia! AFAIU there is no easy way or a specific scenario to reproduce the issue?
And one more question, are you using the default CKEditor 4 lib for React integration (so the one from CDN)? I was thinking it is not caused by some delays in loading stuff via CDN :thinking: 

Anyway, we will try to investigate what's going on here, but it may take some time due to the nature of this issue.

**Comment by fajrulaulia** [comment] 2020-01-21 10:21
All right Thanks, btw I'm not use from CKEditor 4 React integration. I'll change to ckeditor4 react js.

**Comment by jacekbogdanski** [comment] 2022-12-28 09:57
@fajrulaulia the issue was closed by you a long time ago (in 2020) and now it's reopened. Could you share what changed?

**Closed** 2023-04-13 04:34 UTC
